### ISSUE TITLE
cannot find path if path to executable of makeprg quoted

### ISSUE THREAD

**Issue by Konfekt** [mg979/tasks.vim#10]
If parameters are passed to `&makprg` and the path to its executable is (double)quoted (in Microsoft Windows), say by

```
let &makeprg =  shellescape(path) . ' --parameters'
```

then `:Make` cannot find the path. Instead, `:make` works fine.

**Comment by Konfekt** [comment]
Maybe it hinges also on [this Vim patch](https://github.com/vim/vim/commit/d78f03f86045184dfd191f00359baa61e2e79d1f). Behavior changed in version `>= 8.1`.

**Comment by mg979** [comment]
I'll check when I'm on Windows.

**Comment by mg979** [comment]
It should be fixed, can you confirm please? Sorry it took so long.

**Comment by Konfekt** [comment]
Hello, now when the executable, say [autohotkey](https://github.com/Konfekt/vim-compilers/blob/master/compiler/autohotkey.vim), is in `%ProgramFiles%` set to `C:\Program Files`, then `:LMake` returns that the command `"""C:\Program"` could not be found if the path was shell escaped and otherwise `"C:\Program"`.

**Comment by mg979** [comment]
Now it should work, but when you have spaces in the executable you should always put it in double quotes in the command name, because when the command is passed the plugin can't distinguish the executable from the arguments. It works like that also in Windows registry entries and links, so it's how it should be I think. So your command should be like:

    "C:\Program Files\autohotkey\autohotkey.exe" {arguments}
