### ISSUE TITLE
Offer async.vim upstream decoupled from tasks.vim

### ISSUE THREAD

**Issue by Konfekt** [mg979/tasks.vim#8]
Just a suggestion: While [async.vim](https://github.com/mg979/tasks.vim/blob/master/plugin/async.vim) offers commands to spawn the most common commands in the background and therefore should come with Vim (how about asking upstream to include it?), [tasks.vim](https://github.com/mg979/tasks.vim/blob/master/plugin/tasks.vim) extends into Vim the concept of Makefiles and is therefore more specialized.

**Comment by mg979** [comment]
You mean that they should be different plugins? I wouldn't ask to include async.vim anyway because it contains code specific for nvim, and it's not the only plugin of this kind (and barely anybody knows it anyway). It would also need extensive testing (I didn't make tests for this one).

I bundled them together because they're closely related and they don't add much to startup time, only commands are in `plugin` files.

**Comment by Konfekt** [comment]
Yes, this is the only plug-in to run multiple make jobs with output to the respective location lists; very basic functionality not yet available (as much more convenient background jobs) in Vim itself.

**Comment by mg979** [comment]
>run multiple make jobs with output to the respective location lists

Speaking of which, there's currently a problem when using location lists and the command takes long to finish and you are in a different window, it will jump to the first match in the current window. It's something to fix.

**Comment by Konfekt** [comment]
Yes, tracking jobs and location lists is a feat no one dared and such nuisances to be expected.

**Comment by mg979** [comment]
I tried to fix it, maybe it works. I'm closing this for now.
